name: Terraform EC2 Deployment

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to deploy"
        required: true
        default: dev
        type: choice
        options: [dev, uat, prod]

env:
  AWS_REGION: us-east-1

jobs:
  terraform:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    defaults:
      run:
        working-directory: terraform

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          # assume the role based on selected env
          role-to-assume: ${{ fromJson('{
            "dev":  "arn:aws:iam::108471662249:role/github-oidc-role-dev",
            "uat":  "arn:aws:iam::108471662249:role/github-oidc-role-uat",
            "prod": "arn:aws:iam::108471662249:role/github-oidc-role-prod"
          }')[inputs.env] }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Show files (debug)
        run: ls -la && tree -L 2 || true

      - name: Terraform Init (remote backend)
        run: |
          terraform init \
            -backend-config=backend.${{ inputs.env }}.tfvars

      - name: Terraform Validate
        run: terraform validate

      - name: Terraform Plan (${{ inputs.env }})
        run: terraform plan -var-file=envs/${{ inputs.env }}.tfvars -out=tfplan

      - name: Terraform Apply (${{ inputs.env }})
        run: terraform apply -auto-approve tfplan

      - name: Terraform Output (public IP)
        id: tfout
        run: |
          terraform output -json | jq -r '.public_ip.value'

      - name: Publish EC2 link to Summary
        run: |
          IP=$(terraform output -json | jq -r '.public_ip.value')
          echo "## EC2 Deployment Successful" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Public IP:** $IP" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "[Open Website](http://$IP)" >> $GITHUB_STEP_SUMMARY
          echo "[Open EC2 in AWS Console](https://console.aws.amazon.com/ec2/v2/home?region=${AWS_REGION}#Instances:search=$IP)" >> $GITHUB_STEP_SUMMARY
